[Appearance]
style=kvantum-dark
color_scheme_path=/usr/share/color-schemes/KvDark.colors
icon_theme=WhiteSur-dark
standard_dialogs=gtk3

[Font]
general="SF Pro Display,11,-1,0,400,0,0,0,0,0,Regular"

[Interface]
double_click_interval=400
cursor_flash_time=1000
dialog_buttons_have_icons=1
